service: orders
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  stage: dev
  profile: mursal-dev
  environment:
    DATABASE_NAME: "ecomm_dev"

functions:
  getOrders:
    handler: handler.getOrders
    events:
      - http:
          path: /api/v1/getAllOrders
          method: get
          cors: true
  addOrder:
    handler: handler.addOrder
    events:
      - http:
          path: /api/v1/addOrder
          method: post
          cors: true
  updateOrder:
    handler: handler.updateOrder
    events:
      - http:
          path: /api/v1/updateOrder
          method: put
          cors: true
  deleteOrder:
    handler: handler.deleteOrder
    events:
      - http:
          path: /api/v1/deleteOrder
          method: delete
          cors: true
  getOrderById:
    handler: handler.getOrderById
    events:
      - http:
          path: /api/v1/getOrderById
          method: get
          cors: true
