service: products
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  stage: dev
  profile: mursal-dev
  environment:
    DATABASE_NAME: "ecomm_dev"

functions:
  getProducts:
    handler: handler.getProducts
    events:
      - http:
          path: /api/v1/getAllProducts
          method: get
          cors: true
  addProduct:
    handler: handler.addProduct
    events:
      - http:
          path: /api/v1/addProduct
          method: post
          cors: true
  updateProduct:
    handler: handler.updateProduct
    events:
      - http:
          path: /api/v1/updateProduct
          method: put
          cors: true
  deleteProduct:
    handler: handler.deleteProduct
    events:
      - http:
          path: /api/v1/deleteProduct
          method: delete
          cors: true
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: /api/v1/getProductById
          method: get
          cors: true
